#pragma once

// Components list - must have at least one element
// TODO completar
#define _CMPS_LIST_ \
	TRANSFORM, \
	RENDER_TEXTURE, \
	RIGIDBODY, \
	SHAPE, \
	WHITEBALLSCORER, \
	COLORBALLSCORER, \
	WALL, \
	TRYCOLLISION, \
	BUTTON, \
	EVENT_ON_COLLISION, \
	STICK_INPUT, \
	TEXT_DISPLAY, \
	FOLLOW, \
	BALL_EFFECT, \
	BOWLING_EFFECT, \
	QUANTIC_EFFECT, \
	POKEBALL_EFFECT, \
	PETANQUE_EFFECT, \
	ABACUS_EFFECT, \
	CRISTAL_EFFECT, \
	X2_EFFECT, \
	SUBDIVISION_EFFECT, \
	PUSH_OUTSIDE_TRIGGER, \
	FRICTION_MULTIPLIER, \
	EXPLOSIVE_EFFECT, \
	BOXING_GLOVE_STICK, \
	MAGIC_WAND_STICK, \
	GRANADE_LAUCHER_STICK, \
	BALL_HANDLER

// Groups list - must have at least one element
//
#define _GRPS_LIST_ \
	WHITEBALL, \
	EFFECTBALLS, \
	TABLE, \
	PALO, \
	BACKGROUND, \
	SCORE, \
	SHADOWS, \
	POOL_HOLE

// Effect list
// TODO completar	
#define _EFFECT_LIST_ \
	NULO, \
	CRISTAL

// Shape list
#define _SHAPE_LIST_ \
	CIRCLE, \
	CAPSULE, \
	POLYGON
