local fonts = {
    { id = "ARIAL16", file = "../../resources/fonts/ARIAL.ttf", size = 16 },
    { id = "ARIAL24", file = "../../resources/fonts/ARIAL.ttf", size = 24 },
    { id = "ARIAL48", file = "../../resources/fonts/ARIAL.ttf", size = 48 },
    { id = "CAPTURE16", file = "../../resources/fonts/Capture_it.ttf", size = 16},
    { id = "CAPTURE24", file = "../../resources/fonts/Capture_it.ttf", size = 24},
    { id = "CAPTURE48", file = "../../resources/fonts/Capture_it.ttf", size = 48},
    { id = "NES-CHIMERA16", file = "../../resources/fonts/NES-chimera.ttf", size = 16},
    { id = "NES-CHIMERA24", file = "../../resources/fonts/NES-chimera.ttf", size = 24},
    { id = "NES-CHIMERA48", file = "../../resources/fonts/NES-chimera.ttf", size = 48}, 
    { id = "Basteleur-Moonlight16", file = "../../resources/fonts/Basteleur-Moonlight.ttf", size = 16},
    { id = "Basteleur-Moonlight24", file = "../../resources/fonts/Basteleur-Moonlight.ttf", size = 24},
    { id = "Basteleur-Moonlight48", file = "../../resources/fonts/Basteleur-Moonlight.ttf", size = 48},
    { id = "Basteleur-Moonlight60", file = "../../resources/fonts/Basteleur-Moonlight.ttf", size = 60},
    { id = "Basteleur-Bold16", file = "../../resources/fonts/Basteleur-Bold.ttf", size = 16},
    { id = "Basteleur-Bold24", file = "../../resources/fonts/Basteleur-Bold.ttf", size = 24},
    { id = "Basteleur-Bold48", file = "../../resources/fonts/Basteleur-Bold.ttf", size = 48},
    { id = "Basteleur-Bold72", file = "../../resources/fonts/Basteleur-Bold.ttf", size = 72},
    { id = "Bocalupo-Regular16", file = "../../resources/fonts/Bocalupo-Regular.ttf", size = 16},
    { id = "Bocalupo-Regular24", file = "../../resources/fonts/Bocalupo-Regular.ttf", size = 24},
    { id = "Bocalupo-Regular48", file = "../../resources/fonts/Bocalupo-Regular.ttf", size = 48},
    { id = "Bonbance-BoldCondensed16", file = "../../resources/fonts/Bonbance-BoldCondensed.ttf", size = 16},
    { id = "Bonbance-BoldCondensed24", file = "../../resources/fonts/Bonbance-BoldCondensed.ttf", size = 24},
    { id = "Bonbance-BoldCondensed48", file = "../../resources/fonts/Bonbance-BoldCondensed.ttf", size = 48},
    { id = "Aladin-Regular16", file = "../../resources/fonts/Aladin-Regular.ttf", size = 16},
    { id = "Aladin-Regular24", file = "../../resources/fonts/Aladin-Regular.ttf", size = 24},
    { id = "Aladin-Regular30", file = "../../resources/fonts/Aladin-Regular.ttf", size = 30},
    { id = "Aladin-Regular48", file = "../../resources/fonts/Aladin-Regular.ttf", size = 48}
}

return fonts