local images = {
    { id = "fondo", file = "../../resources/images/fondo_blanco.png"},
    { id = "fondo_verde", file = "../../resources/images/fondo_verde.png"},
    { id = "marco2", file = "../../resources/images/marco2.png"},
    { id = "mesa1", file = "../../resources/images/mesa1.png"},
    { id = "mesa1_sombra", file = "../../resources/images/mesa1_sombra.png"},
    { id = "bola_blanca", file = "../../resources/images/bola_blanca.png"},
    { id = "bola_sombra", file = "../../resources/images/bola_sombra.png"},
    { id = "bola_cast_sombra", file = "../../resources/images/bola_cast_sombra.png"},
    { id = "bola_montada", file = "../../resources/images/bola_montada.png"},
    { id = "suelo", file = "../../resources/images/suelo.png"},

    { id = "drawer", file = "../../resources/images/drawer.png"},

    { id = "RectangleMENU", file = "../../resources/images/mainmenu/RectangleMENU.png"},
    { id = "RectangleMENUCorner", file = "../../resources/images/mainmenu/RectangleMENUCorner.png"},
    { id = "RectangleTitle", file = "../../resources/images/RectangleTitle.png"},
    { id = "RectanglePlay", file = "../../resources/images/mainmenu/RectanglePlay.png"},
    { id = "RectangleTutorial", file = "../../resources/images/mainmenu/RectangleTutorial.png"},
    { id = "RectangleControls", file = "../../resources/images/mainmenu/RectangleControls.png"},
    { id = "RectangleCredits", file = "../../resources/images/mainmenu/RectangleCredits.png"},
    { id = "RectangleExit", file = "../../resources/images/mainmenu/RectangleExit.png"},
    { id = "menuBackground", file = "../../resources/images/mainmenu/menuBackground.png"},
    { id = "C", file = "../../resources/images/C.png"},
    { id = "AROM", file = "../../resources/images/AROM.png"},
    { id = "Play", file = "../../resources/images/mainmenu/Play.png"},
    { id = "Tutorial", file = "../../resources/images/mainmenu/Tutorial.png"},
    { id = "Controls", file = "../../resources/images/mainmenu/Controls.png"},
    { id = "Credits", file = "../../resources/images/mainmenu/Credits.png"},
    { id = "Exit", file = "../../resources/images/mainmenu/Exit.png"},
    { id = "fondoMainMenu", file = "../../resources/images/mainmenu/fondoMainMenu.png"},

    { id = "ControlesDe", file = "../../resources/images/controlsmenu/ControlesDe.png"},
    { id = "imagenMenuPausa", file = "../../resources/images/controlsmenu/imagenMenuPausa.png"},
    { id = "Interaccion", file = "../../resources/images/controlsmenu/Interaccion.png"},
    { id = "InteraccionTextPalo", file = "../../resources/images/controlsmenu/InteraccionTextPalo.png"},
    { id = "Inventario", file = "../../resources/images/controlsmenu/Inventario.png"},
    { id = "InventarioText", file = "../../resources/images/controlsmenu/InventarioText.png"},
    { id = "InventarioTextClic", file = "../../resources/images/controlsmenu/InventarioTextClic.png"},
    { id = "InventarioTextPalo1", file = "../../resources/images/controlsmenu/InventarioTextPalo1.png"},
    { id = "MenuPausa", file = "../../resources/images/controlsmenu/MenuPausa.png"},
    { id = "MenuPausaText", file = "../../resources/images/controlsmenu/MenuPausaText.png"},
    { id = "RectangleInteraccionGrande", file = "../../resources/images/controlsmenu/RectangleInteraccionGrande.png"},
    { id = "RectangleInteraccionNombre", file = "../../resources/images/controlsmenu/RectangleInteraccionNombre.png"},
    { id = "RectangleInventario", file = "../../resources/images/controlsmenu/RectangleInventario.png"},
    { id = "RectangleInventarioGrande", file = "../../resources/images/controlsmenu/RectangleInventarioGrande.png"},
    { id = "RectangleMenuPausaGrande", file = "../../resources/images/controlsmenu/RectangleMenuPausaGrande.png"},
    { id = "RectangleMenuPausa", file = "../../resources/images/controlsmenu/RectangleMenuPausa.png"},
    { id = "regresarText", file = "../../resources/images/controlsmenu/regresarText.png"},
    { id = "rewardButtonTextCM", file = "../../resources/images/controlsmenu/rewardButtonText.png"},
    { id = "fondoControls", file = "../../resources/images/controlsmenu/fondoControls.png"},
    { id = "SeletionArrow", file = "../../resources/images/controlsmenu/SeletionArrow.png"},
    { id = "cursor", file = "../../resources/images/cursor.png"},

    { id = "segurosalir", file = "../../resources/images/mainmenu/segurosalir.png"},
    { id = "salir", file = "../../resources/images/mainmenu/salir.png"},
    { id = "cancelar", file = "../../resources/images/mainmenu/cancelar.png"},
    { id = "menu", file = "../../resources/images/mainmenu/menu.png"},

    { id = "texture_NormalStick", file = "../../resources/images/palo1.png"},
    { id = "shadow_NormalStick", file = "../../resources/images/palo1_sombra.png"},
    { id = "texture_WandStick", file = "../../resources/images/magic_wand.png"},
    { id = "shadow_WandStick", file = "../../resources/images/magic_wand_shadow.png"},
    { id = "texture_DonutStick", file = "../../resources/images/donut.png"},
    { id = "shadow_DonutStick", file = "../../resources/images/donut_sombra.png"},
    { id = "texture_GrenadeStick", file = "../../resources/images/lanzagranadas.png"},
    { id = "shadow_GrenadeStick", file = "../../resources/images/lanzagranadas_sombra.png"},
    { id = "texture_BoxingStick", file = "../../resources/images/boxing.png"},
    { id = "shadow_BoxingStick", file = "../../resources/images/boxing_shadow.png"},

    { id = "floor", file = "../../resources/images/floor.png"},
    { id = "scoreSprite", file = "../../resources/images/scoreSprite.png"},
    { id = "roundScoreSprite", file = "../../resources/images/scoring-sheet.png"},
    { id = "roundScorerPup", file = "../../resources/images/RoundScorerPup.png"},
    { id = "roundScorerColt", file = "../../resources/images/RoundScorerColt.png"},
    { id = "roundScorerMax", file = "../../resources/images/RoundScorerMax.png"},
    { id = "reward_description_box", file = "../../resources/images/reward_description_box.png"},
     {id = "inventory_description_box", file = "../../resources/images/inv_description.png"},
    { id = "hole", file = "../../resources/images/hole.png"},
    { id = "shotsSprite", file = "../../resources/images/shots_left.png"},
    { id = "normal_collide_VFX", file = "../../resources/images/normal_collide_VFX.png"},

    { id = "cowboy_hand", file = "../../resources/images/cowboy_hand.png"},
    { id = "cowboy_hand_shadow", file = "../../resources/images/cowboy_hand_shadow.png"},
    { id = "cowboy_table_shadow", file = "../../resources/images/cowboy_table_shadow.png"},
    { id = "sand1", file = "../../resources/images/sand1.png"},
    { id = "sand2", file = "../../resources/images/sand2.png"},
    { id = "sand3", file = "../../resources/images/sand3.png"},
    { id = "sand4", file = "../../resources/images/sand4.png"},
    { id = "sand5", file = "../../resources/images/sand5.png"},
    { id = "sand6", file = "../../resources/images/sand6.png"},
    { id = "sand7", file = "../../resources/images/sand7.png"},
    { id = "sand8", file = "../../resources/images/sand8.png"},
    
    { id = "pyramid_table_shadow", file = "../../resources/images/pyramid_table_shadow.png"},
    { id = "pyramid0", file = "../../resources/images/pyramid0.png"},
    { id = "pyramid1", file = "../../resources/images/pyramid1.png"},
    { id = "pyramid2", file = "../../resources/images/pyramid2.png"},
    { id = "pyramid3", file = "../../resources/images/pyramid3.png"},
    { id = "pyramid4", file = "../../resources/images/pyramid4.png"},
    { id = "pyramid_shadow0", file = "../../resources/images/pyramid_shadow0.png"},
    { id = "pyramid_shadow1", file = "../../resources/images/pyramid_shadow1.png"},
    { id = "pyramid_shadow2", file = "../../resources/images/pyramid_shadow2.png"},
    { id = "pyramid_shadow3", file = "../../resources/images/pyramid_shadow3.png"},
    { id = "pyramid_shadow4", file = "../../resources/images/pyramid_shadow4.png"}, 
    { id = "russian_indicator", file = "../../resources/images/light1.png"}, 
    { id = "russian_hand", file = "../../resources/images/russian_boss.png"},
    { id = "russian_boss_shadow", file = "../../resources/images/russian_boss_shadow.png"},

    { id = "loseButtonText", file = "../../resources/images/lose/loseButtonText.png"},
    { id = "citacionlose0", file = "../../resources/images/lose/citacionlose0.png"},
    { id = "citacionlose1", file = "../../resources/images/lose/citacionlose1.png"},
    { id = "citacionlose2", file = "../../resources/images/lose/citacionlose2.png"},
    { id = "citacionlose3", file = "../../resources/images/lose/citacionlose3.png"},
    { id = "citacionlose4", file = "../../resources/images/lose/citacionlose4.png"},
    { id = "citacionlose5", file = "../../resources/images/lose/citacionlose5.png"},
    { id = "citacionlose6", file = "../../resources/images/lose/citacionlose6.png"},
    { id = "citacionlose7", file = "../../resources/images/lose/citacionlose7.png"},
    { id = "blackscreen", file = "../../resources/images/lose/blackscreen.png"},
    { id = "rewardButtonText", file = "../../resources/images/win/rewardButtonText.png"},
    { id = "youwin", file = "../../resources/images/win/youwin.png"},
    { id = "BowlingEffect", file = "../../resources/images/balleffect_sheets/bowling-sheet.png"},
    { id = "X2Effect", file = "../../resources/images/balleffect_sheets/x2-sheet.png"},
    { id = "AbaccusEffect", file = "../../resources/images/balleffect_sheets/abaco-sheet.png"},
    { id = "CristalEffect", file = "../../resources/images/balleffect_sheets/crystal-sheet.png"},
    { id = "PetanqueEffect", file = "../../resources/images/balleffect_sheets/petanca-sheet.png"},
    { id = "PokeballEffect", file = "../../resources/images/balleffect_sheets/poke-sheet.png"},
    { id = "QuanticEffect", file = "../../resources/images/balleffect_sheets/quantic-sheet.png"},
    { id = "Ignacio", file = "../../resources/images/balleffect_sheets/ignacio-sheet.png"},

    { id = "line", file = "../../resources/images/line.png"},
    { id = "single_BowlingEffect", file = "../../resources/images/bowling.png"},
    { id = "single_X2Effect", file = "../../resources/images/x2.png"},
    { id = "single_AbaccusEffect", file = "../../resources/images/abaco.png"},
    { id = "single_CristalEffect", file = "../../resources/images/cristal.png"},
    { id = "single_PetanqueEffect", file = "../../resources/images/petanca.png"},
    { id = "single_PokeballEffect", file = "../../resources/images/poke.png"},
    { id = "single_QuanticEffect", file = "../../resources/images/quantic.png"},
    { id = "explosion", file = "../../resources/images/explosion.png"},
    { id = "boss_ball", file = "../../resources/images/boss_ball.png"},
    { id = "current_score", file = "../../resources/images/current_score.png"},
    { id = "to_beat_score", file = "../../resources/images/to_beat_score.png"},
    { id = "plus", file = "../../resources/images/plus.png"},

    { id = "carisma_stamp", file = "../../resources/images/permanent_rewards_stamps/carisma.png"},
    { id = "picardia_stamp", file = "../../resources/images/permanent_rewards_stamps/picardia.png"},
    { id = "poder_stamp", file = "../../resources/images/permanent_rewards_stamps/poder.png"},
    { id = "soltura_stamp", file = "../../resources/images/permanent_rewards_stamps/soltura.png"}
}

return images