name: Deploy Quartz site to GitHub Pages + Web molona del juego
 
on:
  push:
    branches:
      - gh-pages
 
permissions:
  contents: read
  pages: write
  id-token: write
 
concurrency:
  group: "pages"
  cancel-in-progress: false
 
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for git info
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install Dependencies
        working-directory: quartz-site
        run: npm ci

      - name: Build Quartz
        working-directory: quartz-site
        run: npx quartz build --output public/wiki

      - name: Copy static HTML to root
        working-directory: quartz-site
        run: cp -r ../docs/. public

      - name: Debug Output
        run: ls -R quartz-site/public

      - name: Clean npm cache
        working-directory: quartz-site
        run: npm cache clean --force
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with: 
          path: quartz-site/public
 
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4